name 'spoon'
maintainer       'maintainer'
maintainer_email 'kouzmine_serguei@carnival.com'
license          'All rights reserved'
description      'Installs/Configures spoon'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.2'
supports         'windows'
# depends          'windows', '>= 1.2.8'
# depends          'powershell'
