default['selenium_node']['display_driver']['install_flavor'] = 'xvfb'
default['selenium_node']['my_platform'] = 'LINUX'
default['selenium_node']['selenium']['version'] = '2.44.0'
default['selenium_node']['selenium']['url'] = \
'http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar'
default['selenium_node']['log4j']['version'] = '1.2.17'
default['selenium_node']['log4j']['url'] = 'http://apache.mirrors.pair.com/logging/log4j/1.2.17/log4j-1.2.17.tar.gz'
default['selenium_node']['hub_port'] = '4444'
default['selenium_node']['node_port'] = '5555'
default['selenium_node']['node'] = 'LINUX'
default['selenium_node']['hub_ip'] = '127.0.0.1'
default['selenium_node']['display_port'] = '99'
