default['selenium']['display_driver']['install_flavor'] = 'xvfb'
default['selenium']['my_platform'] = 'LINUX'
default['selenium']['selenium']['version'] = '2.44.0'
default['selenium']['selenium']['url'] = \
'http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar'
default['selenium']['log4j']['version'] = '1.2.17'
default['selenium']['log4j']['url'] = 'http://apache.mirrors.pair.com/logging/log4j/1.2.17/log4j-1.2.17.tar.gz'
default['selenium']['hub_port'] = '4444'
default['selenium']['node_port'] = '5555'
default['selenium']['node'] = 'LINUX'
default['selenium']['hub_ip'] = '127.0.0.1'
default['selenium']['display_port'] = '99'
