name 'custom_powershell'
maintainer       'maintainer'
maintainer_email 'kouzmine_serguei@carnival.com'
license          'All rights reserved'
description      'Executes various custom powershell scripts'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
supports         'windows'
depends          'windows', '>= 1.2.8'
depends          'powershell'
