default['xvfb']['display_driver']['install_flavor'] = 'xvfb'
default['xvfb']['display_port'] = '99'
default['xvfb']['account_username'] = 'vncuser'
# default['xvfb']['password'] = 'password'
# default['xvfb']['geometry'] = '1192x894'
